version: '3.8'
services:
  wp:
    image: wordpress:php8.1
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./vendor:/var/www/html/vendor
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-config.php:/var/www/html/wp-config.php
    env_file: ../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:80
    restart: always
    depends_on:
      - database
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    ports:
      - 3306:3306
    volumes:
      - wp-db:/var/lib/mysql:delegated
volumes:
  wp-db: ~