name: WordPress Docker Image
on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - apps/wp
jobs:
  build:
    name: Build Image & Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./build
          file: ./apps/wp/Dockerfile
          build-args:
            ACF_PRO_LICENSE=${{ secrets.ACF_PRO_LICENSE }}
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
